"""
Signal-related SQLAlchemy ORM models.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import JSON, String, Text, Numeric, Float
from sqlalchemy.orm import Mapped, mapped_column

from database.models import BaseModel


class SignalModel(BaseModel):
    """
    SQLAlchemy model for trading signals.

    Represents a trading signal generated by a strategy.
    Signals can be LONG, SHORT, CLOSE, or NEUTRAL.
    """

    __tablename__ = "signals"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    strategy_id: Mapped[str] = mapped_column(String(50), index=True)
    symbol: Mapped[str] = mapped_column(String(50))
    signal_type: Mapped[str] = mapped_column(String(50))  # SignalType enum
    confidence: Mapped[float] = mapped_column(Float)
    price: Mapped[float] = mapped_column(Numeric(precision=20, scale=8))
    timestamp: Mapped[datetime] = mapped_column(default=datetime.utcnow, index=True)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    layer_breakdown: Mapped[list] = mapped_column(JSON, default=list)
    meta: Mapped[dict] = mapped_column(JSON, default=dict)


class LayerSignalModel(BaseModel):
    """
    SQLAlchemy model for layer-level signals.

    Represents a signal generated by a single strategy layer.
    Used internally for signal composition and aggregation.
    """

    __tablename__ = "layer_signals"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    layer_id: Mapped[str] = mapped_column(String(50), index=True)
    signal_type: Mapped[str] = mapped_column(String(50))  # SignalType enum
    confidence: Mapped[float] = mapped_column(Float)
    weight: Mapped[float] = mapped_column(Float, default=1.0)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    meta: Mapped[dict] = mapped_column(JSON, default=dict)
