"""
Signal-related Pydantic models.

Defines trading signals and layer signals with their associated enums.
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import uuid4

from enum import Enum

from pydantic import BaseModel, Field, field_validator


class SignalType(str, Enum):
    """Enum for signal types."""

    LONG = "long"
    SHORT = "short"
    CLOSE = "close"
    NEUTRAL = "neutral"


class LayerSignal(BaseModel):
    """
    Represents a signal generated by a single strategy layer.

    Used internally for signal composition and aggregation.
    """

    layer_id: str
    signal_type: SignalType
    confidence: float = Field(ge=0.0, le=1.0)
    weight: float = Field(ge=0.0, le=1.0, default=1.0)
    reasoning: Optional[str] = Field(default=None, max_length=1000)
    metadata: dict = Field(default_factory=dict)


class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.

    Signals can be LONG, SHORT, CLOSE, or NEUTRAL with associated
    confidence and reasoning.
    """

    id: str = Field(default_factory=lambda: f"sig_{uuid4().hex[:8]}")
    strategy_id: str
    symbol: str = Field(min_length=1, description="Trading symbol (e.g., BTC/USDT)")
    signal_type: SignalType
    confidence: float = Field(ge=0.0, le=1.0)
    price: Decimal = Field(gt=Decimal("0"), description="Price at signal generation")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    reasoning: Optional[str] = Field(default=None, max_length=2000)
    layer_breakdown: list[dict] = Field(
        default_factory=list,
        description="Breakdown of signals from each layer",
    )
    metadata: dict = Field(default_factory=dict)

    @field_validator("symbol")
    @classmethod
    def symbol_format(cls, v: str) -> str:
        """Validate and normalize symbol format."""
        return v.upper().strip()

    @field_validator("confidence")
    @classmethod
    def confidence_range(cls, v: float) -> float:
        """Ensure confidence is in valid range."""
        if not 0.0 <= v <= 1.0:
            raise ValueError("Confidence must be between 0 and 1")
        return v
